#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
# task 2.1.3 - sigprocmask syscall 
entry("sigprocmask");
# task 2.1.4 - sigaction syscall
entry("sigaction");
# task 2.1.5 - sigret system call
entry("sigret");
# task 3.2 - kthread_create system call
entry("kthread_create");
# task 3.2 - kthread_id system call 
entry("kthread_id");
# task 3.2 - kthread_join system call
entry("kthread_join");
# task 3.2 - kthread_exit system call
entry("kthread_exit");
# task 4.1 - binary semaphore system calls
entry("bsem_alloc");
entry("bsem_free");
entry("bsem_down");
entry("bsem_up");